### PR TITLE
Unit tests for Utils.JSON.TJSONHelper

### PR DESCRIPTION
**Pull request by JensMertelmeyer**
DUnit test project for `Utils.JSON.TJSONHelper`

### CODE REVIEW

**Comment by JensMertelmeyer** [comment]
Two of the test cases do not pass as I believe `TJsonHelper.Equals(a, b)` should throw an `EArgumentNilException` when either `a` or `b` is `nil`

**Comment by flobernd** [comment]
Thanks for contributing! Would you mind exchanging the TABs with spaces, before I merge your PR?

> Two of the test cases do not pass as I believe `TJsonHelper.Equals(a, b)` should throw an `EArgumentNilException` when either `a` or `b` is `nil`

I would rather like the unit test to not expect an exception in this case. The reason I designed the method like this, is to match the behaviour of `TObject.Equals` for the `nil` edge-case:
```pascal
function TObject.Equals(Obj: TObject): Boolean;
begin
  Result := Obj = Self;
end;
```

What do you think?

**Comment by JensMertelmeyer** [comment]
> Would you mind exchanging the TABs with spaces

I have never done such a hideous thing before so I have to ask: Is converting `↹` to two spaces correct?

> I would rather like the unit test to not expect an exception in this case.

Sure, that's legit. I have altered the test case. But to be in line with [.NET](https://docs.microsoft.com/de-de/dotnet/api/system.object.equals?view=netframework-4.7.1#System_Object_Equals_System_Object_System_Object_) or [Java](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#equals(java.lang.Object,%20java.lang.Object)), it should return `true` if both arguments are `nil`. For now, it throws an access violation.

**Comment by flobernd** [comment]
> I have never done such a hideous thing before so I have to ask: Is converting `↹` to two spaces correct?

Yes, that would be great.

> it should return `true` if both arguments are `nil`. For now, it throws an access violation.

Oh, that indeed is a bug on my side. I'll fix this after merging your PR.

**Comment by flobernd** [comment]
Thanks! Merged. The bug should be fixed as well.

**Pull request merged**
